environment:
  global:
    DISTUTILS_USE_SDK: "1"
    ARCH: "64"
    PYTHON: "C:\\Miniconda3-x64"

  matrix:
    - CONDA_PY: "36"
    - CONDA_PY: "39"

install:
  - CALL "%PYTHON%\\Scripts\\activate.bat"
  - conda config --set always_yes true
  - conda config --set quiet true 
  - conda config --add channels conda-forge
  - conda install boa 
  # Build the compiled extension and run the project tests
  - conda mambabuild tools/conda-recipe --numpy=%CONDA_NUMPY%

build: false
